### ISSUE TITLE
Add Kotlin Space

### ISSUE THREAD

**Issue by zjuhasz** [unitsofmeasurement/uom-spaces#11]
Space can be based on fork of [Physikal](https://github.com/Tenkiv/Physikal)

**Comment by keilw** [comment]
@zjuhasz Thanks for the pointer also to https://github.com/Tenkiv/Physikal. Would you be able to provide a PR? Is the license of Physikal compliant or similar to UoM/JSR363? Except very few cases we have everything based on BSD3. We could use  another license for the Kotlin space if there's a good reason for it, otherwise keeping both the Java and Kotlin parts under the same license might make it easier.

**Comment by ejberry** [comment]
The project now uses BSD3 license, should it be added as a submodule?

**Comment by keilw** [comment]
That is perfectly compatible. Either into https://github.com/unitsofmeasurement/uom-spaces/tree/master/kotlin-space/uom-kotlin as placeholder or if another name or multiple modules were better, it would be under the Kotlin space.
